version: '3'

services:
  hls-transcoder:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - hls-data:/app/hls
      - logs-data:/app/logs
    environment:
      - SOURCE_URL=https://m3u8-prx.onrender.com/willow.m3u8
      - SUPPRESS_LOGS=true
      - CHECK_INTERVAL=10
    restart: always

volumes:
  hls-data:
  logs-data:
